var username;
var age;
var isLoggedIn;
isLoggedIn = true;
var uid;
uid = "oewioijxknkogjdf";
uid = 97;
var myFriends = [];
myFriends.push("Ddd");
var myStuff = [];
myStuff.push("Clothes");
myStuff.push(420);
var myThing;
myThing = { title: "Atlas", pages: 40 };
var myBook;
myBook = { title: "Tidying Up", pages: 128, isReading: false };
