var mysteryBox;
mysteryBox = "Cat";
mysteryBox = false;
mysteryBox = null;
var mysteryStuff;
mysteryStuff.push("Shoes");
mysteryStuff.push(true);
mysteryStuff.push(90);
var mysteryItem;
mysteryItem = { name: true, count: "maybe one" };
